version: '3'

services:

  back:
    image: node:10.16.0
    container_name: back
    ports:
      - 5000:5000
    volumes:
      - ./back:/usr/src/app
    working_dir: /usr/src/app
    command: ["sh", "-c", "npm install && npm start"]

  front:
    image: node:10.16.0
    container_name: front
    ports:
      - 3000:3000
    volumes:
      - ./front:/usr/src/app
    working_dir: /usr/src/app
    links:
      - back
    command: ["sh", "-c", "npm install && npm start"]